// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evklieodtmiquyfusmwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2a2xpZW9kdG1pcXV5ZnVzbXdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MjM0MjgsImV4cCI6MjA2Nzk5OTQyOH0.kvExIc933nIz9X7hG6fWdete7NHhgBD4_fDZpGqJDO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});